#include <stdio.h>
#include <stdlib.h>

#include "pony.h"

static const char *res_debug_c = 
"#include \"pony_fs.h\"\n"
"\n"
"bool pony_resources_are_packed = false;\n"
"\n"
"FSPackedMem fs_find_packed_resource(const char *res_path) {\n"
"\treturn (FSPackedMem){ 0 };\n"
"}\n";

static const char *my_ponygame_h = 
"#ifndef MY_PONYGAME_H // Avoid warning...\n"
"#define MY_PONYGAME_H\n"
"\n"
"/*\n"
" * This file is automatically generated. It contains includes for standard\n"
" * library headers, as well as for generated defines from your code.\n"
" * \n"
" * This is intended to be the only header included in your game code. As such,\n"
" * it is built as a precompiled header.\n"
" */\n"
"\n"
"#include <stdlib.h>\n"
"#include <stdint.h>\n"
"#include <string.h>\n"
"\n"
"#include \"ponygame.h\"\n"
"\n"
"#include \"my.res.h\"\n"
"\n";

void generate_file_res_debug_c() {
	FILE *out = fopen(".ponygame/res_debug.c", "w");

	fputs(res_debug_c, out);

	fclose(out);
}

void pack_res(const char *fname, FILE *out, FILE *list, size_t *index) {
	FILE *in = fopen(fname, "rb");

	printf("packing file %s...\n", fname);

	size_t start = *index;
	for(;;) {
		int next = fgetc(in);
		if(next == EOF) break;

		fprintf(out, "%d,", next);
		(*index)++;
	}
	size_t size = *index - start;
	fprintf(list, "if(!strcmp(res_path,\"%s\")) { result.ptr = data + %llu; result.length = %llu; return result; }", fname, start, size);

	fclose(in);
}

void generate_file_res_release_c(ProjectFiles *pf) {
	FILE *out = fopen(".ponygame/res_release.c", "w");
	FILE *list = fopen(".ponygame/res_release_tree.h", "w");

	fputs("#include <string.h>\n#include \"pony_fs.h\"\n\n", out);
	fputs("bool pony_resources_are_packed = true;\n\n", out);

	size_t index = 0;
	
	fputs("static uint8_t data[] = {", out);

	for(int i = 0; i < pf->spritesheet_count; ++i) {
		char tmp[256] = { 0 };
		snprintf(tmp, 256, "pngcrush -ow .ponygame/spritesheet%04d.png", i);
		system(tmp);

		snprintf(tmp, 256, ".ponygame/spritesheet%04d.png", i);
		pack_res(tmp, out, list, &index);
	}

	foreach(tex, pf->tex_list, {
		if(tex->use_raw_file) {
			char tmp[1024] = { 0 };
			snprintf(tmp, 1024, "pngcrush -ow %s", tex->image_source);
			system(tmp);

			pack_res(tex->image_source, out, list, &index);
		}
	})

	printf("packing %d sounds\n", ls_length(pf->path_list.snd_infos));
	foreach(snd_info, pf->path_list.snd_infos, {
		if(!snd_info.build_output) {
			printf("pack file warning: bad .snd file '%s'\n", snd_info.snd_path);
		}

		pack_res(snd_info.build_output, out, list, &index);
	})

	fputs("};\n", out);

	fputs("FSPackedMem fs_find_packed_resource(const char *res_path) {\n", out);
	fputs("FSPackedMem result = { 0 };\n", out);
	fputs("#include \"res_release_tree.h\"\n", out);
	fputs("return result;\n}\n", out);

	fclose(list);
	fclose(out);
}

void generate_file_pony_source_c(ProjectFiles *pf) {
	FILE *out = fopen(".ponygame/my.ponygame.c", "w");

	fputs("#include \"my.ponygame.h\"\n", out);

	foreach(pony, pf->pony_list, {
		if(!pony->type_name) continue;
		fprintf(out, "node_meta_defines(%s)\n", pony->type_name);
	})

	foreach(pony, pf->pony_list, {
		if(pony->has_construct) {
			fprintf(out, "extern void %s(%s *self);\n", pony->construct_func, pony->type_name);
			fprintf(out, "void %s_impl(void *ptr) { %s(ptr); }\n", pony->construct_func, pony->construct_func);
		}
		if(pony->has_destruct) {
			fprintf(out, "extern void %s(%s *self);\n", pony->destruct_func, pony->type_name);
			fprintf(out, "void %s_impl(void *ptr) { %s(ptr); }\n", pony->destruct_func, pony->destruct_func);
		}
		if(pony->has_tick) {
			fprintf(out, "extern void %s(%s *self, %sTree *tree);\n", pony->tick_func, pony->type_name, pony->type_name);
			fprintf(out, "void %s_impl(void *ptr, void *unused_tree) {\n", pony->tick_func);
			if(pony->has_tree) {
				fprintf(out, "\tvoid *tree = &((%s*)ptr)->tree;\n", pony->type_name);
			}
			else {
				fputs("\tvoid *tree = NULL;\n", out);
			}
			fprintf(out, "\t%s(ptr, tree);\n}\n", pony->tick_func);
		}
	})

	fputs("\nvoid pony_init_user_nodes() {\n", out);
	foreach(pony, pf->pony_list, {
		if(!pony->type_name) continue;
		const char *construct = pony->has_construct ? pony->construct_func : "NULL";
		const char *construct_impl = pony->has_construct ? "_impl" : "";
		const char *destruct = pony->has_destruct ? pony->destruct_func : "NULL";
		const char *destruct_impl = pony->has_destruct ? "_impl" : "";
		const char *tick = pony->has_tick ? pony->tick_func : "NULL";\
		const char *tick_impl = pony->has_tick ? "_impl" : "";
		fprintf(out, "\tnode_meta_initialize(\n"
			"\t\t%s,\n"
			"\t\t&node_header(%s),\n"
			"\t\t%s%s,\n"
			"\t\t%s%s,\n"
			"\t\t%s%s,\n"
			"\t\tBLOCKS_LARGE\n"
		"\t)\n", pony->type_name, pony->type_base_class, construct, construct_impl, tick, tick_impl, destruct, destruct_impl);
	})
	fputs("}\n", out);

	fclose(out);
}

void generate_file_my_ponygame_h(ProjectFiles *pf) {
	FILE *out = fopen(".ponygame/my.ponygame.h", "w");

	// Write static header portion
	fputs(my_ponygame_h, out);

	// Trees must be generated before the other types -- because trees are used
	// as value types, while all the fields they have are reference types and
	// so don't need to be declared previously.
	foreach(pony, pf->pony_list, {
		// This loop is specifically for Node types with an associated tree
		if(!pony->type_name) continue;

		if(!pony->has_tree) {
			// Still need a type definition for these trees, just for ease of use...
			// Just declare it equal to void.
			fprintf(out, "typedef void %sTree;\n\n", pony->type_name);
			continue;
		}

		fprintf(out, "typedef struct %sTree {\n", pony->type_name);

		foreach(entry, pony->tree_entries, {
			// Print entries to tree -- need to use struct Something * format,
			// as these types haven't necessarily been declared yet
			fprintf(out, "\tstruct %s *%s;\n", entry.type, entry.name);
		})

		fprintf(out, "} %sTree;\n\n", pony->type_name);
	})

	foreach(pony, pf->pony_list, {
		if(!pony->type_name) continue;
		fprintf(out, "#define FieldList_%s \\\n", pony->type_name);
		fprintf(out, "FieldList_%s", pony->type_base_class);
		if(pony->has_tree) {
			// The tree must be a stack-allocated type, so that all the pointers
			// are stored with the node.
			fprintf(out, " \\\nstruct %sTree tree;", pony->type_name);
		}
		// Generate slashes before each new line, always have a space at the end
		// of a line as well
		foreach(field, pony->struct_fields, {
			fprintf(out, " \\\n%s", field);
		})
		fputs("\n\n", out);
	})

	foreach(pony, pf->pony_list, {
		if(!pony->type_name) continue;
		fprintf(out, "node_from_field_list(%s)\n", pony->type_name);
	})

	fputs("\n", out);

	foreach(pony, pf->pony_list, {
		// Don't print the comments, etc for empty headers
		if(ls_empty(pony->header_lines)) continue;

		// Comment for readability
		fprintf(out, "/* --- %s --- */\n\n", pony->file_path);
		// Copy user header lines to output
		foreach(line, pony->header_lines, {
			fputs(line, out);
		})
		fputs("\n\n", out);
	})
	
	// Close the header guard
	fputs("#endif", out);
	fclose(out);
}

void generate_file_pony_c_from_pony(const char *path, PonyFileInfo *pony) {
	FILE *out = fopen(path, "w");

	fputs("#include \"my.ponygame.h\"\n\n", out);

	fputs("// Automatically copied header lines. May not be useful.\n", out);
	foreach(line, pony->header_lines, {
		fprintf(out, "%s\n", line);
	})

	fputs("\n", out);
	if(pony->construct_func) {
		fprintf(out, "void %s(%s *self) {\n\t\n}\n\n", pony->construct_func, pony->type_name);
	}
	else {
		fprintf(out, "// void construct_%s(%s *self) { }\n\n", pony->type_name, pony->type_name);
	}

	if(pony->destruct_func) {
		fprintf(out, "void %s(%s *self) {\n\t\n}\n\n", pony->destruct_func, pony->type_name);
	}
	else {
		fprintf(out, "// void destruct_%s(%s *self) { }\n\n", pony->type_name, pony->type_name);
	}

	if(pony->tick_func) {
		fprintf(out, "void %s(%s *self, %sTree *tree) {\n\t\n}\n\n", pony->tick_func, pony->type_name, pony->type_name);
	}
	else {
		fprintf(out, "// void tick_%s(%s *self, %sTree *tree) { }\n\n", pony->type_name, pony->type_name, pony->type_name);
	}

	fclose(out);
}

void generate_file_blank_main_c() {
	FILE *out = fopen("main.c", "w");

	fputs("#include \"my.ponygame.h\"\n", out);
	fputs("#include \"pony.main.h\"\n\n", out);

	fputs("impl_begin {\n\t\n}\n\n", out);
	fputs("impl_tick_start {\n\t\n}\n\n", out);
	fputs("impl_tick_end {\n\t\n}\n", out);

	fclose(out);
}