#ifndef PONY_KEY
	#define PONY_KEY(keyname, sdl_scancode)
#endif

// Need to do this so that the preprocessor doesn't get confused about complex
// numbers.
// Complex numbers are not currently foreseen to be useful for the game scripting
// itself, so this is kind of fine..?
#undef I

PONY_KEY(Space,SDL_SCANCODE_SPACE)
PONY_KEY(A,SDL_SCANCODE_A)
PONY_KEY(B,SDL_SCANCODE_B)
PONY_KEY(C,SDL_SCANCODE_C)
PONY_KEY(D,SDL_SCANCODE_D)
PONY_KEY(E,SDL_SCANCODE_E)
PONY_KEY(F,SDL_SCANCODE_F)
PONY_KEY(G,SDL_SCANCODE_G)
PONY_KEY(H,SDL_SCANCODE_H)
PONY_KEY(I,SDL_SCANCODE_I)
PONY_KEY(J,SDL_SCANCODE_J)
PONY_KEY(K,SDL_SCANCODE_K)
PONY_KEY(L,SDL_SCANCODE_L)
PONY_KEY(M,SDL_SCANCODE_M)
PONY_KEY(N,SDL_SCANCODE_N)
PONY_KEY(O,SDL_SCANCODE_O)
PONY_KEY(P,SDL_SCANCODE_P)
PONY_KEY(Q,SDL_SCANCODE_Q)
PONY_KEY(R,SDL_SCANCODE_R)
PONY_KEY(S,SDL_SCANCODE_S)
PONY_KEY(T,SDL_SCANCODE_T)
PONY_KEY(U,SDL_SCANCODE_U)
PONY_KEY(V,SDL_SCANCODE_V)
PONY_KEY(W,SDL_SCANCODE_W)
PONY_KEY(X,SDL_SCANCODE_X)
PONY_KEY(Y,SDL_SCANCODE_Y)
PONY_KEY(Z,SDL_SCANCODE_Z)

PONY_KEY(Left,SDL_SCANCODE_LEFT)
PONY_KEY(Right,SDL_SCANCODE_RIGHT)
PONY_KEY(Up,SDL_SCANCODE_UP)
PONY_KEY(Down,SDL_SCANCODE_DOWN)

PONY_KEY(Escape,SDL_SCANCODE_ESCAPE)